[Draft] Introduce CI with github actions
matsumo0922/android-training-template pull request #35
Opened 2024-08-15 06:29 UTC by matsumo0922

#33 を先にレビューお願いします 🙏 

## 修正内容
- closes #1 
- github actions を用いて簡単な CI を導入します
  - Detekt のチェック
  - テストの実行

## レビューレベルの設定
- [ ] まったく見ないでApproveする(基本的には非推奨。)
- [x] ぱっとみて違和感がないかチェックしてApproveする
- [ ] 仕様レベルまで理解して、仕様通りに動くかある程度検証、動作確認までしてApproveする
- [ ] その他 (以下にコメント記載)

## レビュー観点
- CI が定義通り動作するか確認してほしいです
- 必要/不必要な権限がないか
- 他に CI で確認すべき項目がないか

## スクリーンショット
- N/A

## 備考
- N/A

2024-08-15 06:48 UTC, matsumo0922 commented on build-logic/src/main/java/jp/co/yumemi/droidtraining/Detekt.kt
> +            output.set(rootProject.layout.buildDirectory.file("reports/detekt/merge.xml"))
サブモジュールでの Detekt 実行結果を一つにまとめるタスクです。
基本的に CI でのみ用います。

2024-08-15 06:48 UTC, matsumo0922 commented on .gitignore
> +.kotlin
Kotlin のバージョンを 2.0.0~ にしたので `.kotlin` フォルダが作成されるようになりました。
同時の修正で申し訳ないですが、簡単な変更なので同時に ignore しています。

2024-08-15 06:58 UTC, TBSten commented on .gitignore
> +.kotlin
[memo]
あらら... 自分も見逃してました 🙏 
そういう意味で行くと #9 でcompose導入する際も気をつけないといけないですねー

2024-08-15 07:41 UTC, TBSten requested changes
コメント多めですが 自分の理解が足りてないところもあるかもなので、「いやここ見逃してるよ」等あればツッコミ入れてもらえると助かります 🙏

2024-08-15 07:41 UTC, TBSten commented on .github/workflows/call-lint.yml
> +          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
[imo]
自分の知識不足もあるかもですが、 [`gradle/actions/setup-gradle`](https://github.com/gradle/actions/tree/main/setup-gradle) というaction を利用した方が[キャッシュ周りの面倒も見てくれる](https://github.com/gradle/actions/tree/main/setup-gradle)ので、特に理由がなければこちらに置き換えた方がシンプルにできるかもしれません👀

2024-08-15 07:41 UTC, TBSten commented on build-logic/src/main/java/jp/co/yumemi/droidtraining/Detekt.kt
> +            output.set(rootProject.layout.buildDirectory.file("reports/detekt/merge.xml"))
この手のコメントはPRのコメントよりもソースコードにコメントした方がいいかなと思いました（後でソースコード見た人に意図を伝えるため）

2024-08-15 07:41 UTC, TBSten commented on .github/workflows/pull-request-ci.yml
> +    uses: ./.github/workflows/call-test.yml
[memo]
ファイルに分割されていてとっても見やすいですねー👍

2024-08-15 07:41 UTC, TBSten commented on .github/workflows/call-lint.yml
> +        run: chmod +x ./gradlew
[imho]
[`gradle/actions/setup-gradle`](https://github.com/gradle/actions/tree/main/setup-gradle) を使うと不要になるかもです... (未検証ですが[actionのソースコードにそれっぽい記述](https://github.com/gradle/actions/blob/b51fcf4d6c62967b980aeba27b7e747d74e20c53/sources/src/execution/gradlew.ts#L44)がある)

2024-08-15 07:41 UTC, TBSten commented on .github/workflows/call-test.yml
> +      - name: Build app
[must]
テストを走らせるので `Run test` とかの方が適切だと思いました。

2024-08-15 07:41 UTC, TBSten commented on .github/workflows/pull-request-ci.yml
> +  cancel-in-progress: true
[good]
concurrencyの設定だ... 雑にしがちなので、きちんと設定してて頭が上がらないですー👍

2024-08-15 07:41 UTC, TBSten commented on .github/workflows/call-test.yml
> +        run: chmod +x ./gradlew
[imo]
この辺りも [`gradle/actions/setup-gradle`](https://github.com/gradle/actions/tree/main/setup-gradle) を使うと省略できそうな気がしました。

2024-08-15 07:41 UTC, TBSten commented on .github/workflows/call-lint.yml
> +          ruby-version: 3.1.3
[must]
今回は danger等のruby製のツールは使ってない認識なので、Rubyのセットアップはいらないと思いましたー

2024-08-15 07:56 UTC, matsumo0922 commented on .github/workflows/call-lint.yml
> +          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
便利な action があったんですね...
`setup-gradle` を使用するようにしました 326fe05

2024-08-15 07:56 UTC, matsumo0922 commented on .github/workflows/call-lint.yml
> +        run: chmod +x ./gradlew
`setup-gradle` を使用するようにしました 326fe05

2024-08-15 07:56 UTC, matsumo0922 commented on .github/workflows/call-test.yml
> +      - name: Build app
確かに 🙏 
修正しました 326fe05

2024-08-15 07:56 UTC, matsumo0922 commented on .github/workflows/call-test.yml
> +        run: chmod +x ./gradlew
`setup-gradle` を使用するようにしました 326fe05

2024-08-15 07:57 UTC, matsumo0922 commented on .github/workflows/call-lint.yml
> +          ruby-version: 3.1.3
削除しました 326fe05

2024-08-15 09:53 UTC, TBSten commented on .github/workflows/call-lint.yml
> +  pull-requests: write
[memo]
TODO step　にかけた気がするので調べる

2024-08-15 10:11 UTC, TBSten commented on .github/workflows/call-lint.yml
> +  pull-requests: write
step単位ではなくjob単位でした💦
https://docs.github.com/ja/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#setting-the-github_token-permissions-for-a-specific-job

```yaml
jobs:
  detekt:
    # ...
    permissions:
      pull-requests: write
    # ...
```

2024-08-15 10:54 UTC, sobaya-0141 commented on .github/workflows/call-test.yml
> +        run: ./gradlew test
全く修正の必要はなくもしご存じなければの前提で知識の共有的な意味で[kover](https://github.com/Kotlin/kotlinx-kover)と言う物を使うとhtmlなどでテストレポートを出力してくれて便利です！

偉い人からテストのレポート見やすい形で出せや〜とか言われるお仕事の時に導入するとhtmlでポイっと渡せて便利です！

2024-08-16 01:10 UTC, matsumo0922 commented on .github/workflows/call-lint.yml
> +  pull-requests: write
job 単位で権限付与するようにしました ad6120a

2024-08-16 03:50 UTC, matsumo0922 commented on .github/workflows/call-test.yml
> +        run: ./gradlew test
`kover` を導入し、カバレッジレポートを GitHub  Pages の方にデプロイするようにしました！ 2df1003

2024-08-16 03:56 UTC, TBSten approved these changes
ペアプロありがとうございましたー！
前のPRで見落としてた箇所の細かい修正 :bigkansha: です！

<img src="https://tbsten.me/tbsten-lgtm.png" alt="LGTM" width="250" />

2024-08-16 03:56 UTC, TBSten commented on build-logic/src/main/java/jp/co/yumemi/droidtraining/AndroidGradleDsl.kt
> +        }
[memo]
#32 で見落としてました 🙏

2024-08-16 03:56 UTC, Seo-4d696b75 approved these changes

2024-08-16 03:56 UTC, matsumo0922 commented
レビューありがとうございました 🙇

2024-08-16 03:56 UTC, merged

2024-08-19 00:13 UTC, TBSten commented on .github/workflows/pull-request-test.yml
> +  cancel-in-progress: false
[memo]
しっかり[ドキュメント](https://docs.github.com/ja/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#%E4%BE%8B-%E7%89%B9%E5%AE%9A%E3%81%AE%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%81%A7%E9%80%B2%E8%A1%8C%E4%B8%AD%E3%81%AE%E3%82%B8%E3%83%A7%E3%83%96%E3%81%AE%E3%81%BF%E3%82%92%E5%8F%96%E3%82%8A%E6%B6%88%E3%81%99) みるとtrue/false以外にも式を指定できるらしいので、ここら辺をうまく使うと「別のPRのjobはキューするが同じPRのjobはキャンセルする」みたいなこともできるかもですね...

2024-08-19 02:40 UTC, matsumo0922 commented on .github/workflows/pull-request-test.yml
> +  cancel-in-progress: false
当時は混乱していましたが、今落ち着いて考えてみると他と同様に、以下のようにすれば「同じPRの同じワークフローはキャンセルする」という意味になるのでは...？と思ってきました。

```
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true
```

2024-08-19 03:10 UTC, TBSten commented on .github/workflows/pull-request-test.yml
> +  cancel-in-progress: false
[memo]
（確認会の際にもお話しした通りですが、） 別PRで同時並行でデプロイjobが走ると よろしくないので PRの番号(`github.event.number`) は含めないほうが良さそう。