Implement Main Screen with Compose
matsumo0922/android-training-template pull request #40
Opened 2024-08-19 06:15 UTC by matsumo0922

## 修正内容
- closes #10
- メイン画面を Compose で作成します
- 表示する内容はダミーです

## レビューレベルの設定
- [ ] まったく見ないでApproveする(基本的には非推奨。)
- [x] ぱっとみて違和感がないかチェックしてApproveする
- [ ] 仕様レベルまで理解して、仕様通りに動くかある程度検証、動作確認までしてApproveする
- [ ] その他 (以下にコメント記載)

## レビュー観点
- ConstraintLayout Composable の使い方は正しいか
- UI は一旦ダミーとなっています

## スクリーンショット
| After |
| - |
|<img src=https://github.com/user-attachments/assets/1b1a794c-3fe4-4f6f-b9d6-c58b6248685f width=250 >|

## 備考
- N/A

2024-08-19 06:29 UTC, matsumo0922 commented on app/src/main/res/values-night/themes.xml
> +    <style name="Theme.Droidtraining" parent="Theme.MaterialComponents.DayNight.NoActionBar">
issue にはツールバーが表示されている画像が貼られていましたが、Figma には無かったため削除しました。
また、表示が必要な場合は Compose  の TopAppBar で対応します。

2024-08-19 06:29 UTC, matsumo0922 commented on app/src/main/java/jp/co/yumemi/droidtraining/MainActivity.kt
> +            val darkScrim = Color.argb(0x80, 0x1b, 0x1b, 0x1b)
AndroidX で定義されているデフォルトの色を適用しています
FYI: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:activity/activity/src/main/java/androidx/activity/EdgeToEdge.kt;l=35-38;drc=27e7d52e8604a080133e8b842db10c89b4482598

2024-08-19 06:29 UTC, matsumo0922 commented on core/ui/src/main/java/jp/co/yumemi/droidtraining/core/ui/extensions/PreviewExtensions.kt
> +annotation class ComponentPreviews
現状はライトテーマのみですが、`YumemiTheme` はダークモードの適応も考慮されているので、二つのプレビューができるように `ComponentPreviews` というアノテーションをあらかじめ定義しておきます。

2024-08-19 06:29 UTC, matsumo0922 commented on gradle.properties
> +android.nonTransitiveRClass=false
全てのリソース（drawable や string）を `:core:ui` モジュールに置いているため、`nonTransitiveRClass` を false にします。
ビルド速度は若干遅くなってしまいますが、リソースの一貫性と利便性のために許容したいです。

2024-08-19 07:40 UTC, TBSten requested changes
細かいところはコメントしましたが、UIの実装に関しては完璧かと思いますー👏

2024-08-19 07:40 UTC, TBSten commented on app/src/main/java/jp/co/yumemi/droidtraining/MainActivity.kt
> +            DisposableEffect(shouldUseDarkTheme) {
[must]
`onDispose` が空なのであれば `LaunchedEffect` で十分かと思います。

refs: https://developer.android.com/develop/ui/compose/side-effects#disposableeffect

2024-08-19 07:40 UTC, TBSten commented on gradle/libs.versions.toml
> +androidxComposeConstraintLayout = "1.0.1"
[memo]
1.0.1が最新版なので大丈夫そう
https://developer.android.com/jetpack/androidx/releases/constraintlayout

2024-08-19 07:40 UTC, TBSten commented on gradle/libs.versions.toml
> +    "compose-constraint-layout",
[imo]
`compose-constraint-layout` は :app モジュールでしか利用しませんが、ここに含めてしまうと :core:ui モジュールにも含まれてしまいます。

bundles.ui-implementations ではなく :app モジュールのdependenciesに直接指定して モジュールあたりのビルドサイズを小さくすべきだと思いました。

2024-08-19 08:06 UTC, matsumo0922 commented on app/src/main/java/jp/co/yumemi/droidtraining/MainActivity.kt
> +            DisposableEffect(shouldUseDarkTheme) {
僕もコードを追ったわけではないですが、`LaunchedEffect ` は Dispatch を必要とするため、`DisposableEffect` より後に実行されるようです。この処理は一刻も早く実行する必要があるため、わずかな違いかもしれませんが`DisposableEffect` を用いるようにしています。

FYI: https://github.com/android/nowinandroid/pull/330/files#r999831539

2024-08-19 08:11 UTC, matsumo0922 commented on gradle/libs.versions.toml
> +    "compose-constraint-layout",
確かにです 🙏 

compose の ConstraintLayout はできるだけ触りたくない（宣言的UIと相性が悪いと思っている）ので他のモジュールで触ってしまうことがないようにという面も加えて、 bundle から外しました 8118a97

2024-08-19 10:08 UTC, TBSten approved these changes
LaunchedEffectとDisposableEffectの都市伝説もうちょっと調べてみたいです....!

<img src="https://tbsten.me/tbsten-lgtm.png" alt="LGTM" width="250" />

2024-08-20 01:09 UTC, matsumo0922 commented
レビューありがとうございました 🙏

2024-08-20 01:09 UTC, merged