Implement loading view on MainScreen
matsumo0922/android-training-template pull request #44
Opened 2024-08-20 03:33 UTC by matsumo0922

## 修正内容
- closes #17 
- UiState を sealed interface 化して対応するか迷いましたが、今回は ViewEvent に `Loading` というイベントを足して対応します

## レビューレベルの設定

- [ ] まったく見ないでApproveする(基本的には非推奨。)
- [x] ぱっとみて違和感がないかチェックしてApproveする
- [ ] 仕様レベルまで理解して、仕様通りに動くかある程度検証、動作確認までしてApproveする
- [ ] その他 (以下にコメント記載)

## レビュー観点
- LoadingView を表示する過程は問題ないか
- ViewModel で withContext を呼び出している点や、Dispatcher をコンストラクタ型渡していない点（テストのことを考えていない）などは後ほど対応するのでレビュー範囲外です

## スクリーンショット
| After |
| - |
|<video src=https://github.com/user-attachments/assets/975e968e-bc7d-4ba0-8c18-eafe03f61f75 >|

## 備考
- N/A

2024-08-20 04:26 UTC, TBSten requested changes
数点コメントしましたー

2024-08-20 04:26 UTC, TBSten commented on app/src/main/java/jp/co/yumemi/droidtraining/components/MainScreen.kt
> +                    .padding(it),
[good]
LoadingViewにはpaddingがかからないようにするのナイスですねー 👏

2024-08-20 04:26 UTC, TBSten commented on app/src/main/java/jp/co/yumemi/droidtraining/components/MainScreen.kt
> +            }
[imo]
AnimatedVisibilityやModifier.fillMaxSize(), background()もLoadingViewに含めて使いまわせるようにしてもいいかなと思いました。

2024-08-20 04:35 UTC, Seo-4d696b75 commented on app/src/main/java/jp/co/yumemi/droidtraining/components/MainScreen.kt
> +    if (viewEvent is MainWeatherViewEvent.ShowError) {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
この実装だと`viewEvent`を「状態」として扱っているため、`MainWeatherViewEvent`はstateに命名変更して`MainWeatherUiState`に含めたほうが良いかもです

2024-08-20 05:22 UTC, matsumo0922 commented on app/src/main/java/jp/co/yumemi/droidtraining/components/MainScreen.kt
> +            }
修正しました18280e1

2024-08-20 05:26 UTC, matsumo0922 commented on app/src/main/java/jp/co/yumemi/droidtraining/components/MainScreen.kt
> +    if (viewEvent is MainWeatherViewEvent.ShowError) {
その通りですね... 🙏 

ただフラグで管理するというのは避けたいので、ViewEvent から `MainWeatherScreenState` と名前を変更して対応します。本来の ScreenState 方式であれば `ScreenState.Idle` に UiState を含み、Idle 時のみ UiState を提供するのが良さそうではありますが、今回は「ローディング中やエラー時にもコンテンツを表示したい（要 UiState）」であるため、UiState と ScreenState を分けて提供します。

2024-08-20 15:35 UTC, matsumo0922 commented on app/src/main/java/jp/co/yumemi/droidtraining/components/MainScreen.kt
> +    if (viewEvent is MainWeatherViewEvent.ShowError) {
FYI: https://yumemi.slack.com/archives/C07B7A9FQVC/p1724134374761209?thread_ts=1724133024.780459&cid=C07B7A9FQVC

2024-08-21 02:35 UTC, Seo-4d696b75 commented on app/src/main/java/jp/co/yumemi/droidtraining/components/MainScreen.kt
> +    if (viewEvent is MainWeatherViewEvent.ShowError) {
> 本来の ScreenState 方式であれば ScreenState.Idle に UiState を含み、Idle 時のみ UiState を提供するのが良さそう

ここら辺は設計思想に依るのでお好きな方法で大丈夫です 🙆‍♂️ 
案件などチーム開発ではプロジェクト初期段階で共通の設計方針を定めることが多いです

2024-08-21 02:35 UTC, Seo-4d696b75 approved these changes

2024-08-21 03:09 UTC, matsumo0922 commented
レビューありがとうございました 🙏

2024-08-21 03:09 UTC, merged